### ISSUE TITLE
Ask for Scripts and CKPT

### ISSUE THREAD

**Issue by SihengLi99** [ellenmellon/INSCIT#1]
Hi,

Good Job !
Well, Can you share the training, evaluation scripts and ckpt ?
We hope to follow this insightful work !

Thanks

**Comment by ellenmellon** [comment]
Hi, thanks a lot for your interest! Sorry for the delay, but we are working on cleaning up everything now and will upload the training and eval scripts in the next few days! Will update on the thread when it's ready.
